# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170114_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 1, 14, 18, 28, 1, 127547, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
